"""Add User table

Revision ID: 378337844832
Revises: 76c2eeb9b321
Create Date: 2026-02-20 14:23:28.824117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378337844832'
down_revision = '76c2eeb9b321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
